version: 0.2

phases:
  install:
    commands:
      - apt-get update -y
      - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
      - echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
      - apt-get update -y
      - apt-get install -y yarn
      - echo for installing serverless
      - cd server
      - yarn global add serverless
      - yarn install
      - echo for local serverless developement
      - cd ../client
      - yarn install

  build:
    commands:
      - cd ../server
      - sls deploy
      - sls info > info.txt
      - cat info.txt
      - echo Build complete of server
      - LAMBDA_URL=$(grep -oP "(https:\/\/)[a-zA-Z0-9]+\.[a-z]+\-[a-z]+\.[a-z]{2}\-[a-z]+\-[0-9]{1}\.[a-z]+\.[a-z]{3}\/[a-z]+$" info.txt)
      - echo $LAMBDA_URL
      - pwd
      - cd ../client
      - REACT_APP_BACKEND_URL=$LAMBDA_URL yarn run build
      - echo Build complete of client
      - echo deployed

cache:
  paths:
    - 'client/node_modules/**/*'
    - 'server/node_modules/**/*'

artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: client/build

role: arn:aws:iam::730627384046:role/service-role/codebuild-als-service-role
