version: 0.2

phases:
  install:
    commands:
      - apt-get update -y
      - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
      - echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
      - apt-get update -y
      - apt-get install -y yarn
      - echo for installing serverless
      - cd server
      - yarn global add serverless
      - yarn install
      - echo for local serverless developement
      - cd ../client
      - yarn install

  build:
    commands:
      - cd ../server
      - sls deploy
      - echo Build complete of server
      - pwd
      - cd ../client
      - echo $REACT_APP_GW_URL
      - echo ${REACT_APP_GW_URL}
      - echo $(REACT_APP_GW_URL)
      - yarn run build
      - echo Build complete of client
      - echo deployed

cache:
  paths:
    - 'client/node_modules/**/*'
    - 'server/node_modules/**/*'

artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: client/build

role: arn:aws:iam::730627384046:role/service-role/codebuild-als-service-role
