service: als-server-left

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: ap-southeast-2

functions:
  app:
    handler: src/index.handler
    events:
      - http:
          path: /{proxy+}
          method: get
